DutchTreat/DutchTreat/ViewModels/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DutchTreat.ViewModels
{
  public class ContactViewModel
  {
    [Required]
    [MinLength(5)]
    public string Name { get; set; }
    [Required]
    [EmailAddress]
    public string Email { get; set; }
    [Required]
    public string Subject { get; set; }
    [Required]
    [MaxLength(250, ErrorMessage = "Too Long")]
    public string Message { get; set; }
  }
}

DutchTreat/DutchTreat/Controllers/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DutchTreat.Data;
using DutchTreat.Services;
using DutchTreat.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace DutchTreat.Controllers
{
  public class AppController : Controller
  {
    private readonly IMailService _mailService;
        private readonly IDutchRepository _repo;

        public AppController(IMailService mailService, IDutchRepository repo)
    {
      _mailService = mailService;
            this._repo = repo;
        }

    public IActionResult Index()
    {
      return RedirectToAction("Shop");
    }

    [HttpGet("contact")]
    public IActionResult Contact()
    {
      return View();
    }

    [HttpPost("contact")]
    public IActionResult Contact(ContactViewModel model)
    {
      if (ModelState.IsValid)
      {
        // Send the email
        _mailService.SendMessage("shawn@wildermuth.com", model.Subject, $"From: {model.Name} - {model.Email}, Message: {model.Message}");
        ViewBag.UserMessage = "Mail Sent";
        ModelState.Clear();
      }

      return View();
    }

    public IActionResult About()
    {
      ViewBag.Title = "About Us";

      return View();
    }

        public IActionResult Shop()
        {
            var products = _repo.GetAllProducts();

            return View(products);
        }
  }
}

DutchTreat/DutchTreat/Views/App/About.cshtml
<h2>About Us</h2>
<p>More to follow</p>

DutchTreat/DutchTreat/Views/App/Contact.cshtml
@model ContactViewModel
@{
  ViewBag.Title = "Contact Us";
}
@section Scripts {
  <script src="~/node_modules/jquery-validation/dist/jquery.validate.min.js"></script>
  <script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
}

  <div class="col-md-6 offset-md-3">
      <div class="card card-body bg-light">
          <form method="post">
              <div asp-validation-summary="ModelOnly"></div>
              <div class="form-group">
                  <label asp-for="Name">Your Name:</label>

                  <input asp-for="Name" class="form-control" />
                  <span asp-validation-for="Name" class="text-danger"></span>
              </div>
              <div class="form-group">
                  <label asp-for="Email">Email:</label>

                  <input type="email" asp-for="Email" class="form-control"/>
                  <span asp-validation-for="Email" class="text-danger"></span>
              </div>
              <div class="form-group">
                  <label asp-for="Subject">Subject:</label>

                  <input type="text" asp-for="Subject" class="form-control"/>
                  <span asp-validation-for="Subject" class="text-danger"></span>
              </div>
              <div class="form-group">
                  <label asp-for="Message">Message:</label>

                  <textarea rows="4" asp-for="Message" class="form-control"></textarea>
                  <span asp-validation-for="Message" class="text-danger"></span>
              </div>
              <div class="form-group">
                  <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-envelope"></i> Send Message</button>
                  <div class="text-success">@ViewBag.UserMessage</div>
              </div>
          </form>
      </div>
  </div>

DutchTreat/DutchTreat/Views/App/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


@model IEnumerable<Product>

<h1>Products</h1>
<p>product count: @Model.Count()</p>

<div class="row">
    @foreach (var p in Model)
    {
        <div class="col-md-3">
            <div class="border bg-light p-1">
                <img src="~/img/@(p.ArtId).jpg" class="img-fluid" alt="@p.Title" />
                <h3>@p.Category - @p.Size</h3>
                <ul>
                    <li>Price: $@p.Price</li>
                    <li>Artist: @p.Artist</li>
                    <li>Title: @p.Title</li>
                    <li>Description: @p.ArtDescription</li>
                </ul>
                <button id="buyButton" class="btn btn-success">Buy</button>
            </div>
        </div>
    }
</div>

@*<div class="row">
    <div class="col-md-9">
        <div class="product-info">
            <img src="~/img/VanGogh.jpg" />
            <h3>Mug</h3>
            <ul class="product-props">
                <li>Price: $9.99</li>
                <li>Artist: Van Gogh</li>
                <li>Title: </li>
                <li>Description: Self-portrait</li>
            </ul>
            <button id="buyButton" class="btn btn-success">Buy</button>
        </div>

        <div id="theForm">
            <form>
                <label>Your Name:</label>
                <br />
                <input />
                <br />
                <label>Email:</label>
                <br />
                <input type="email" />
                <br />
                <label>Subject:</label>
                <br />
                <input type="text" />
                <br />
                <label>Message:</label>
                <br />
                <textarea rows="4"></textarea>
                <br />
                <input type="submit" value="Send Message" />
            </form>
        </div>

        <div>
            <div id="loginToggle">Login</div>
            <form class="popup-form">
                <div>
                    <label>Username</label>
                    <input />
                </div>
                <div>
                    <label>Password</label>
                    <input type="password" />
                </div>
                <div>
                    <input type="checkbox" />
                    <label>Remember Me?</label>
                </div>
                <div>
                    <input type="submit" value="Login" />
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-3">
        <p>this is second column</p>
    </div>
</div>*@

DutchTreat/DutchTreat/Views/App/Shop.cshtml
@model IEnumerable<Product>

<h1>Products</h1>
<p>product count: @Model.Count()</p>

<div class="row">
    @foreach (var p in Model)
    {
        <div class="col-md-3">
            <div class="border bg-light p-1">
                <img src="~/img/@(p.ArtId).jpg" class="img-fluid" alt="@p.Title" />
                <h3>@p.Category - @p.Size</h3>
                <ul>
                    <li>Price: $@p.Price</li>
                    <li>Artist: @p.Artist</li>
                    <li>Title: @p.Title</li>
                    <li>Description: @p.ArtDescription</li>
                </ul>
                <button id="buyButton" class="btn btn-success">Buy</button>
            </div>
        </div>
    }
</div>

DutchTreat/DutchTreat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Sample Website: @ViewBag.Title</title>
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/node_modules/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
    <header class="container">
        <nav class="navbar navbar-dark bg-dark navbar-expand-md">
            <h1 class="navbar-brand"><i class="fa fa-paint-brush"></i> Welcome</h1>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#theMenu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="theMenu" class="navbar-collapse collapse">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link" asp-controller="App" asp-action="Shop">Home</a></li>
                </ul>
            </div>
        </nav>
    </header>
    <section class="container">
        <h2 class="text-center">@ViewBag.Title</h2>
        @RenderBody()
    </section>


    <script src="~/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="~/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/index.js"></script>
    @RenderSection("scripts", false)
</body>
</html>